"""empty message

Revision ID: 09b430f105c4
Revises: cb77578e54e5
Create Date: 2023-03-21 21:53:40.726655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b430f105c4'
down_revision = 'cb77578e54e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.add_column('coordinates', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'coordinates', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coordinates', type_='foreignkey')
    op.drop_column('coordinates', 'area_id')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
