"""empty message

Revision ID: 205fb8347b73
Revises: d354e0955a36
Create Date: 2023-03-18 20:16:46.189092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205fb8347b73'
down_revision = 'd354e0955a36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coordinates_id'), 'coordinates', ['id'], unique=False)
    op.drop_index('ix_vessels_mmsi', table_name='vessels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vessels_mmsi', 'vessels', ['mmsi'], unique=False)
    op.drop_index(op.f('ix_coordinates_id'), table_name='coordinates')
    op.drop_table('coordinates')
    # ### end Alembic commands ###
