"""empty message

Revision ID: 45b83a879abe
Revises: 4800df7572a6
Create Date: 2023-03-22 09:35:20.662049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b83a879abe'
down_revision = '4800df7572a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vessels', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vessels', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vessels', type_='foreignkey')
    op.drop_column('vessels', 'country_id')
    # ### end Alembic commands ###
