"""empty message

Revision ID: d354e0955a36
Revises: e2a06e4e6b18
Create Date: 2023-03-18 18:14:34.177164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd354e0955a36'
down_revision = 'e2a06e4e6b18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.drop_index('ix_users_phone', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
